services:
  mysql:
    image: mysql:8
    container_name: mysql_saas_fs_api
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${NAME_DB}
      MYSQL_USER: ${USERNAME}
      MYSQL_PASSWORD: ${PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"
